version: 2
project_name: makefilehub

# Skip build - binaries are pre-built by CI matrix jobs
builds:
  - id: linux-amd64
    skip: true
    goos: [linux]
    goarch: [amd64]
  - id: linux-arm64
    skip: true
    goos: [linux]
    goarch: [arm64]
  - id: darwin-amd64
    skip: true
    goos: [darwin]
    goarch: [amd64]
  - id: darwin-arm64
    skip: true
    goos: [darwin]
    goarch: [arm64]

archives:
  - id: linux-amd64
    builds: [linux-amd64]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_amd64"
    files:
      - src: dist/x86_64-unknown-linux-gnu/makefilehub
        dst: makefilehub
        info:
          mode: 0755
      - README.md
      - LICENSE
      - config.example.toml

  - id: linux-arm64
    builds: [linux-arm64]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_linux_arm64"
    files:
      - src: dist/aarch64-unknown-linux-gnu/makefilehub
        dst: makefilehub
        info:
          mode: 0755
      - README.md
      - LICENSE
      - config.example.toml

  - id: darwin-amd64
    builds: [darwin-amd64]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_amd64"
    files:
      - src: dist/x86_64-apple-darwin/makefilehub
        dst: makefilehub
        info:
          mode: 0755
      - README.md
      - LICENSE
      - config.example.toml

  - id: darwin-arm64
    builds: [darwin-arm64]
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_darwin_arm64"
    files:
      - src: dist/aarch64-apple-darwin/makefilehub
        dst: makefilehub
        info:
          mode: 0755
      - README.md
      - LICENSE
      - config.example.toml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  github:
    owner: Fuabioo
    name: makefilehub
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

brews:
  - name: makefilehub
    repository:
      owner: Fuabioo
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Fuabioo/makefilehub
    description: General-purpose MCP server for build systems (Makefile, justfile, scripts)
    license: MIT
    install: |
      bin.install "makefilehub"
    test: |
      system "#{bin}/makefilehub", "--version"
